### PR TITLE
preserve spaces in values

### PR DESCRIPTION
**Pull request by jkt628**
e.g.,
--plugin 'bootconfig:inline|hdmi_cvt=1024 600 60 6 0 0 0'

### CODE REVIEW

**Comment by jkt628** [comment]
force-pushed without eliminating dangling space on line endings

**Comment by gitbls** [comment]
Thanks for the fixes. I'm not going to merge this fix because a) my copy of sdm is already modified and I don't want to wrestle with git today, and b) it's easier to incorporate the actual changes than it would be to merge and then clean up the dangling spaces on line endings.

I thought I had caught all the non-quoted string uses. Sigh!

**Comment by jkt628** [comment]
i think this is new code from last month

**Comment by gitbls** [comment]
> i think this is new code from last month

😵 You're absolutely correct. I duffed adding the code for plugin lists. No excuse!

**Pull request closed without merging**
